### ISSUE TITLE
Fresh/clean install - does not respond

### ISSUE THREAD

**Issue by patrickjane** [MrJohnZoidberg/Snips-Wetter#6]
I did a complete clean install of raspbian stretch on a raspberry pi 3 today, and I've successfully installed snips 0.63. I have installed the assistant using `sam`, and its up and running:

```
Wildfire:~ s710$ sam status

Connected to device 10.0.0.30

OS version ................... Raspbian GNU/Linux 9 (stretch)
Installed assistant .......... Home assistant
Language ..................... de
Hotword ...................... hey_snips
ASR engine ................... snips
Status ....................... Live

Service status:

snips-analytics .............. (not running)
snips-asr .................... 0.63.3 (running)
snips-audio-server ........... 0.63.3 (running)
snips-dialogue ............... 0.63.3 (running)
snips-hotword ................ 0.63.3 (running)
snips-nlu .................... 0.63.3 (running)
snips-skill-server ........... 0.63.3 (running)
snips-tts .................... 0.63.3 (running)
```

However, when trying to ask for the weather, it seems like the skill/intent is not recognized, no matter what I say:

```
[21:03:42] [Hotword] detected on site default, for model hey_snips
[21:03:42] [Asr] was asked to stop listening on site default
[21:03:42] [Hotword] was asked to toggle itself 'off' on site default
[21:03:42] [Dialogue] session with id '03ffd07c-1602-4fb9-a8ca-872a33e204cb' was started on site default
[21:03:42] [AudioServer] was asked to play a wav of 41.1 kB with id 'fc9e5496-279e-481b-9c7d-559b01903ff1' on site default
[21:03:58] [Dialogue] session with id '03ffd07c-1602-4fb9-a8ca-872a33e204cb' was ended on site default. The session was ended because one of the component didn't respond in a timely manner
[21:03:58] [Asr] was asked to stop listening on site default
[21:03:58] [Hotword] was asked to toggle itself 'on' on site default
```

This is the first time I am working with snips, so I don't know what might still be missing. What should I do?

[edit] Also I want to add that during the first installation of the assitant with both your "Snips-Wetter" and "Snips-Wecker" apps there was an error during `sam install assistant`. There was something complaining about requiring sudo access but no available tty. Unfortunately I didnt capture those errors.
After a second installation or `sam install skills` there are no more errors.

Could this be an issue or is this normal?

**Comment by patrickjane** [comment]
Okay I found the solution. The issue is not with `Snips-Wetter`, the issue is with `AudioServer` not able to play a feedback sound.
I disabled feedbacks in `/etc/snips.toml` and afterwards it worked. I can now query weather just fine.

I have yet to find out why the feedback sounds dont work, but it has nothing to do with `Snips-Wetter`.

I am sorry for opening this issue, please disregard it.

**Comment by dominiczedler** [comment]
No problem :)
